//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 16.0.32413.511
// 
namespace FinalProject.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="castumeres", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class castumeres : FinalProject.ServiceReference1.BaseEntity {
        
        private string adresseField;
        
        private System.DateTime date_birthField;
        
        private string family_nameField;
        
        private string id_castumerField;
        
        private FinalProject.ServiceReference1.category kod_categoryField;
        
        private FinalProject.ServiceReference1.city kod_cityField;
        
        private string mailField;
        
        private string pelephoneField;
        
        private string private_nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                if ((object.ReferenceEquals(this.adresseField, value) != true)) {
                    this.adresseField = value;
                    this.RaisePropertyChanged("adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_birth {
            get {
                return this.date_birthField;
            }
            set {
                if ((this.date_birthField.Equals(value) != true)) {
                    this.date_birthField = value;
                    this.RaisePropertyChanged("date_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string family_name {
            get {
                return this.family_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.family_nameField, value) != true)) {
                    this.family_nameField = value;
                    this.RaisePropertyChanged("family_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_castumer {
            get {
                return this.id_castumerField;
            }
            set {
                if ((object.ReferenceEquals(this.id_castumerField, value) != true)) {
                    this.id_castumerField = value;
                    this.RaisePropertyChanged("id_castumer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.category kod_category {
            get {
                return this.kod_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_categoryField, value) != true)) {
                    this.kod_categoryField = value;
                    this.RaisePropertyChanged("kod_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.city kod_city {
            get {
                return this.kod_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_cityField, value) != true)) {
                    this.kod_cityField = value;
                    this.RaisePropertyChanged("kod_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pelephone {
            get {
                return this.pelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.pelephoneField, value) != true)) {
                    this.pelephoneField = value;
                    this.RaisePropertyChanged("pelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string private_name {
            get {
                return this.private_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.private_nameField, value) != true)) {
                    this.private_nameField = value;
                    this.RaisePropertyChanged("private_name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.city))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.gauides))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.menuyim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.typ_menuyim_price_))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.Chugim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.typ_chugim))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.rishum_to_lesson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FinalProject.ServiceReference1.castumeres))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="category", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class category : FinalProject.ServiceReference1.BaseEntity {
        
        private int kod_categoryField;
        
        private string name_categoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_category {
            get {
                return this.kod_categoryField;
            }
            set {
                if ((this.kod_categoryField.Equals(value) != true)) {
                    this.kod_categoryField = value;
                    this.RaisePropertyChanged("kod_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_category {
            get {
                return this.name_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.name_categoryField, value) != true)) {
                    this.name_categoryField = value;
                    this.RaisePropertyChanged("name_category");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="city", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class city : FinalProject.ServiceReference1.BaseEntity {
        
        private int kod_cityField;
        
        private string name_cityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_city {
            get {
                return this.kod_cityField;
            }
            set {
                if ((this.kod_cityField.Equals(value) != true)) {
                    this.kod_cityField = value;
                    this.RaisePropertyChanged("kod_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_city {
            get {
                return this.name_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.name_cityField, value) != true)) {
                    this.name_cityField = value;
                    this.RaisePropertyChanged("name_city");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gauides", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class gauides : FinalProject.ServiceReference1.BaseEntity {
        
        private string adresse_guaidField;
        
        private System.DateTime dateBirth_guaidField;
        
        private string family_guaidField;
        
        private FinalProject.ServiceReference1.city kod_cityField;
        
        private int kod_guaidField;
        
        private string name_guaidField;
        
        private string tel_guaidField;
        
        private int vetekField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresse_guaid {
            get {
                return this.adresse_guaidField;
            }
            set {
                if ((object.ReferenceEquals(this.adresse_guaidField, value) != true)) {
                    this.adresse_guaidField = value;
                    this.RaisePropertyChanged("adresse_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateBirth_guaid {
            get {
                return this.dateBirth_guaidField;
            }
            set {
                if ((this.dateBirth_guaidField.Equals(value) != true)) {
                    this.dateBirth_guaidField = value;
                    this.RaisePropertyChanged("dateBirth_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string family_guaid {
            get {
                return this.family_guaidField;
            }
            set {
                if ((object.ReferenceEquals(this.family_guaidField, value) != true)) {
                    this.family_guaidField = value;
                    this.RaisePropertyChanged("family_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.city kod_city {
            get {
                return this.kod_cityField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_cityField, value) != true)) {
                    this.kod_cityField = value;
                    this.RaisePropertyChanged("kod_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_guaid {
            get {
                return this.kod_guaidField;
            }
            set {
                if ((this.kod_guaidField.Equals(value) != true)) {
                    this.kod_guaidField = value;
                    this.RaisePropertyChanged("kod_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_guaid {
            get {
                return this.name_guaidField;
            }
            set {
                if ((object.ReferenceEquals(this.name_guaidField, value) != true)) {
                    this.name_guaidField = value;
                    this.RaisePropertyChanged("name_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_guaid {
            get {
                return this.tel_guaidField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_guaidField, value) != true)) {
                    this.tel_guaidField = value;
                    this.RaisePropertyChanged("tel_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vetek {
            get {
                return this.vetekField;
            }
            set {
                if ((this.vetekField.Equals(value) != true)) {
                    this.vetekField = value;
                    this.RaisePropertyChanged("vetek");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="menuyim", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class menuyim : FinalProject.ServiceReference1.BaseEntity {
        
        private bool IspayField;
        
        private System.DateTime first_dateField;
        
        private FinalProject.ServiceReference1.castumeres id_castumerField;
        
        private int kod_manuiField;
        
        private FinalProject.ServiceReference1.typ_menuyim_price_ kod_typmanuiField;
        
        private System.DateTime last_dateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ispay {
            get {
                return this.IspayField;
            }
            set {
                if ((this.IspayField.Equals(value) != true)) {
                    this.IspayField = value;
                    this.RaisePropertyChanged("Ispay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime first_date {
            get {
                return this.first_dateField;
            }
            set {
                if ((this.first_dateField.Equals(value) != true)) {
                    this.first_dateField = value;
                    this.RaisePropertyChanged("first_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.castumeres id_castumer {
            get {
                return this.id_castumerField;
            }
            set {
                if ((object.ReferenceEquals(this.id_castumerField, value) != true)) {
                    this.id_castumerField = value;
                    this.RaisePropertyChanged("id_castumer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_manui {
            get {
                return this.kod_manuiField;
            }
            set {
                if ((this.kod_manuiField.Equals(value) != true)) {
                    this.kod_manuiField = value;
                    this.RaisePropertyChanged("kod_manui");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.typ_menuyim_price_ kod_typmanui {
            get {
                return this.kod_typmanuiField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_typmanuiField, value) != true)) {
                    this.kod_typmanuiField = value;
                    this.RaisePropertyChanged("kod_typmanui");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime last_date {
            get {
                return this.last_dateField;
            }
            set {
                if ((this.last_dateField.Equals(value) != true)) {
                    this.last_dateField = value;
                    this.RaisePropertyChanged("last_date");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="typ_menuyim_price_", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class typ_menuyim_price_ : FinalProject.ServiceReference1.BaseEntity {
        
        private int kod_typmanuiField;
        
        private int numLesson_weekField;
        
        private int num_monthField;
        
        private int priseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_typmanui {
            get {
                return this.kod_typmanuiField;
            }
            set {
                if ((this.kod_typmanuiField.Equals(value) != true)) {
                    this.kod_typmanuiField = value;
                    this.RaisePropertyChanged("kod_typmanui");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numLesson_week {
            get {
                return this.numLesson_weekField;
            }
            set {
                if ((this.numLesson_weekField.Equals(value) != true)) {
                    this.numLesson_weekField = value;
                    this.RaisePropertyChanged("numLesson_week");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_month {
            get {
                return this.num_monthField;
            }
            set {
                if ((this.num_monthField.Equals(value) != true)) {
                    this.num_monthField = value;
                    this.RaisePropertyChanged("num_month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prise {
            get {
                return this.priseField;
            }
            set {
                if ((this.priseField.Equals(value) != true)) {
                    this.priseField = value;
                    this.RaisePropertyChanged("prise");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chugim", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class Chugim : FinalProject.ServiceReference1.BaseEntity {
        
        private string day_lessonField;
        
        private System.DateTime hour_lessonField;
        
        private FinalProject.ServiceReference1.category kod_categoryField;
        
        private FinalProject.ServiceReference1.gauides kod_guaidField;
        
        private int kod_lessonField;
        
        private FinalProject.ServiceReference1.typ_chugim kod_typLessonField;
        
        private int max_atendanceField;
        
        private int min_atendanceField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string day_lesson {
            get {
                return this.day_lessonField;
            }
            set {
                if ((object.ReferenceEquals(this.day_lessonField, value) != true)) {
                    this.day_lessonField = value;
                    this.RaisePropertyChanged("day_lesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime hour_lesson {
            get {
                return this.hour_lessonField;
            }
            set {
                if ((this.hour_lessonField.Equals(value) != true)) {
                    this.hour_lessonField = value;
                    this.RaisePropertyChanged("hour_lesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.category kod_category {
            get {
                return this.kod_categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_categoryField, value) != true)) {
                    this.kod_categoryField = value;
                    this.RaisePropertyChanged("kod_category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.gauides kod_guaid {
            get {
                return this.kod_guaidField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_guaidField, value) != true)) {
                    this.kod_guaidField = value;
                    this.RaisePropertyChanged("kod_guaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_lesson {
            get {
                return this.kod_lessonField;
            }
            set {
                if ((this.kod_lessonField.Equals(value) != true)) {
                    this.kod_lessonField = value;
                    this.RaisePropertyChanged("kod_lesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.typ_chugim kod_typLesson {
            get {
                return this.kod_typLessonField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_typLessonField, value) != true)) {
                    this.kod_typLessonField = value;
                    this.RaisePropertyChanged("kod_typLesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_atendance {
            get {
                return this.max_atendanceField;
            }
            set {
                if ((this.max_atendanceField.Equals(value) != true)) {
                    this.max_atendanceField = value;
                    this.RaisePropertyChanged("max_atendance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int min_atendance {
            get {
                return this.min_atendanceField;
            }
            set {
                if ((this.min_atendanceField.Equals(value) != true)) {
                    this.min_atendanceField = value;
                    this.RaisePropertyChanged("min_atendance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="typ_chugim", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class typ_chugim : FinalProject.ServiceReference1.BaseEntity {
        
        private int kod_typLessonField;
        
        private string name_lessonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kod_typLesson {
            get {
                return this.kod_typLessonField;
            }
            set {
                if ((this.kod_typLessonField.Equals(value) != true)) {
                    this.kod_typLessonField = value;
                    this.RaisePropertyChanged("kod_typLesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_lesson {
            get {
                return this.name_lessonField;
            }
            set {
                if ((object.ReferenceEquals(this.name_lessonField, value) != true)) {
                    this.name_lessonField = value;
                    this.RaisePropertyChanged("name_lesson");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rishum_to_lesson", Namespace="http://schemas.datacontract.org/2004/07/model")]
    public partial class rishum_to_lesson : FinalProject.ServiceReference1.BaseEntity {
        
        private System.DateTime date_rishumField;
        
        private bool is_mustPayField;
        
        private bool is_perfumenceField;
        
        private FinalProject.ServiceReference1.Chugim kod_lessonField;
        
        private FinalProject.ServiceReference1.menuyim kod_manuiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_rishum {
            get {
                return this.date_rishumField;
            }
            set {
                if ((this.date_rishumField.Equals(value) != true)) {
                    this.date_rishumField = value;
                    this.RaisePropertyChanged("date_rishum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_mustPay {
            get {
                return this.is_mustPayField;
            }
            set {
                if ((this.is_mustPayField.Equals(value) != true)) {
                    this.is_mustPayField = value;
                    this.RaisePropertyChanged("is_mustPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_perfumence {
            get {
                return this.is_perfumenceField;
            }
            set {
                if ((this.is_perfumenceField.Equals(value) != true)) {
                    this.is_perfumenceField = value;
                    this.RaisePropertyChanged("is_perfumence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.Chugim kod_lesson {
            get {
                return this.kod_lessonField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_lessonField, value) != true)) {
                    this.kod_lessonField = value;
                    this.RaisePropertyChanged("kod_lesson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalProject.ServiceReference1.menuyim kod_manui {
            get {
                return this.kod_manuiField;
            }
            set {
                if ((object.ReferenceEquals(this.kod_manuiField, value) != true)) {
                    this.kod_manuiField = value;
                    this.RaisePropertyChanged("kod_manui");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCastumeres", ReplyAction="http://tempuri.org/IService1/GetAllCastumeresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.castumeres>> GetAllCastumeresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGauides", ReplyAction="http://tempuri.org/IService1/GetAllGauidesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.gauides>> GetAllGauidesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckCastumerIfExist", ReplyAction="http://tempuri.org/IService1/CheckCastumerIfExistResponse")]
        System.Threading.Tasks.Task<bool> CheckCastumerIfExistAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckcityIfExist", ReplyAction="http://tempuri.org/IService1/CheckcityIfExistResponse")]
        System.Threading.Tasks.Task<bool> CheckcityIfExistAsync(string ncity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Checkchugifexcist", ReplyAction="http://tempuri.org/IService1/CheckchugifexcistResponse")]
        System.Threading.Tasks.Task<bool> CheckchugifexcistAsync(string namech);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustById", ReplyAction="http://tempuri.org/IService1/GetCustByIdResponse")]
        System.Threading.Tasks.Task<FinalProject.ServiceReference1.castumeres> GetCustByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCastumer", ReplyAction="http://tempuri.org/IService1/AddCastumerResponse")]
        System.Threading.Tasks.Task<int> AddCastumerAsync(FinalProject.ServiceReference1.castumeres s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddManui", ReplyAction="http://tempuri.org/IService1/AddManuiResponse")]
        System.Threading.Tasks.Task AddManuiAsync(FinalProject.ServiceReference1.menuyim n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllChugim", ReplyAction="http://tempuri.org/IService1/GetAllChugimResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.Chugim>> GetAllChugimAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTyp_Chugims", ReplyAction="http://tempuri.org/IService1/GetAllTyp_ChugimsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.typ_chugim>> GetAllTyp_ChugimsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLessonsInWeekForCustomer", ReplyAction="http://tempuri.org/IService1/GetLessonsInWeekForCustomerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.rishum_to_lesson>> GetLessonsInWeekForCustomerAsync(int ccodeManuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetManuy", ReplyAction="http://tempuri.org/IService1/GetManuyResponse")]
        System.Threading.Tasks.Task<FinalProject.ServiceReference1.menuyim> GetManuyAsync(int codeManuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllcity", ReplyAction="http://tempuri.org/IService1/GetAllcityResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.city>> GetAllcityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllcategory", ReplyAction="http://tempuri.org/IService1/GetAllcategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.category>> GetAllcategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTypmanui", ReplyAction="http://tempuri.org/IService1/GetAllTypmanuiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.typ_menuyim_price_>> GetAllTypmanuiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetManuyToCust", ReplyAction="http://tempuri.org/IService1/GetManuyToCustResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.menuyim>> GetManuyToCustAsync(FinalProject.ServiceReference1.castumeres id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodtotypmanuy", ReplyAction="http://tempuri.org/IService1/GetCodtotypmanuyResponse")]
        System.Threading.Tasks.Task<int> GetCodtotypmanuyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodtomenuyim", ReplyAction="http://tempuri.org/IService1/GetCodtomenuyimResponse")]
        System.Threading.Tasks.Task<int> GetCodtomenuyimAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodtotypchugim", ReplyAction="http://tempuri.org/IService1/GetCodtotypchugimResponse")]
        System.Threading.Tasks.Task<int> GetCodtotypchugimAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodtocity", ReplyAction="http://tempuri.org/IService1/GetCodtocityResponse")]
        System.Threading.Tasks.Task<int> GetCodtocityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addtypchug", ReplyAction="http://tempuri.org/IService1/AddtypchugResponse")]
        System.Threading.Tasks.Task<int> AddtypchugAsync(FinalProject.ServiceReference1.typ_chugim t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addcity", ReplyAction="http://tempuri.org/IService1/AddcityResponse")]
        System.Threading.Tasks.Task<int> AddcityAsync(FinalProject.ServiceReference1.city c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addtypmanui", ReplyAction="http://tempuri.org/IService1/AddtypmanuiResponse")]
        System.Threading.Tasks.Task<int> AddtypmanuiAsync(FinalProject.ServiceReference1.typ_menuyim_price_ t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addlesson", ReplyAction="http://tempuri.org/IService1/AddlessonResponse")]
        System.Threading.Tasks.Task<int> AddlessonAsync(FinalProject.ServiceReference1.Chugim c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNumLessonfree", ReplyAction="http://tempuri.org/IService1/GetNumLessonfreeResponse")]
        System.Threading.Tasks.Task<int> GetNumLessonfreeAsync(int codeManuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delate", ReplyAction="http://tempuri.org/IService1/delateResponse")]
        System.Threading.Tasks.Task<int> delateAsync(FinalProject.ServiceReference1.castumeres c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delatguaid", ReplyAction="http://tempuri.org/IService1/delatguaidResponse")]
        System.Threading.Tasks.Task<int> delatguaidAsync(FinalProject.ServiceReference1.gauides g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delateciey", ReplyAction="http://tempuri.org/IService1/delatecieyResponse")]
        System.Threading.Tasks.Task<int> delatecieyAsync(FinalProject.ServiceReference1.city c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/delatetypchug", ReplyAction="http://tempuri.org/IService1/delatetypchugResponse")]
        System.Threading.Tasks.Task<int> delatetypchugAsync(FinalProject.ServiceReference1.typ_chugim t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addlesontomanui", ReplyAction="http://tempuri.org/IService1/AddlesontomanuiResponse")]
        System.Threading.Tasks.Task<int> AddlesontomanuiAsync(FinalProject.ServiceReference1.rishum_to_lesson r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlrishum", ReplyAction="http://tempuri.org/IService1/GetAlrishumResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.rishum_to_lesson>> GetAlrishumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addgauid", ReplyAction="http://tempuri.org/IService1/AddgauidResponse")]
        System.Threading.Tasks.Task<int> AddgauidAsync(FinalProject.ServiceReference1.gauides g);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodtogauid", ReplyAction="http://tempuri.org/IService1/GetCodtogauidResponse")]
        System.Threading.Tasks.Task<int> GetCodtogauidAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FinalProject.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FinalProject.ServiceReference1.IService1>, FinalProject.ServiceReference1.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.castumeres>> GetAllCastumeresAsync() {
            return base.Channel.GetAllCastumeresAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.gauides>> GetAllGauidesAsync() {
            return base.Channel.GetAllGauidesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> CheckCastumerIfExistAsync(string id) {
            return base.Channel.CheckCastumerIfExistAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CheckcityIfExistAsync(string ncity) {
            return base.Channel.CheckcityIfExistAsync(ncity);
        }
        
        public System.Threading.Tasks.Task<bool> CheckchugifexcistAsync(string namech) {
            return base.Channel.CheckchugifexcistAsync(namech);
        }
        
        public System.Threading.Tasks.Task<FinalProject.ServiceReference1.castumeres> GetCustByIdAsync(string id) {
            return base.Channel.GetCustByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> AddCastumerAsync(FinalProject.ServiceReference1.castumeres s) {
            return base.Channel.AddCastumerAsync(s);
        }
        
        public System.Threading.Tasks.Task AddManuiAsync(FinalProject.ServiceReference1.menuyim n) {
            return base.Channel.AddManuiAsync(n);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.Chugim>> GetAllChugimAsync() {
            return base.Channel.GetAllChugimAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.typ_chugim>> GetAllTyp_ChugimsAsync() {
            return base.Channel.GetAllTyp_ChugimsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.rishum_to_lesson>> GetLessonsInWeekForCustomerAsync(int ccodeManuy) {
            return base.Channel.GetLessonsInWeekForCustomerAsync(ccodeManuy);
        }
        
        public System.Threading.Tasks.Task<FinalProject.ServiceReference1.menuyim> GetManuyAsync(int codeManuy) {
            return base.Channel.GetManuyAsync(codeManuy);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.city>> GetAllcityAsync() {
            return base.Channel.GetAllcityAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.category>> GetAllcategoryAsync() {
            return base.Channel.GetAllcategoryAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.typ_menuyim_price_>> GetAllTypmanuiAsync() {
            return base.Channel.GetAllTypmanuiAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.menuyim>> GetManuyToCustAsync(FinalProject.ServiceReference1.castumeres id) {
            return base.Channel.GetManuyToCustAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> GetCodtotypmanuyAsync() {
            return base.Channel.GetCodtotypmanuyAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodtomenuyimAsync() {
            return base.Channel.GetCodtomenuyimAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodtotypchugimAsync() {
            return base.Channel.GetCodtotypchugimAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodtocityAsync() {
            return base.Channel.GetCodtocityAsync();
        }
        
        public System.Threading.Tasks.Task<int> AddtypchugAsync(FinalProject.ServiceReference1.typ_chugim t) {
            return base.Channel.AddtypchugAsync(t);
        }
        
        public System.Threading.Tasks.Task<int> AddcityAsync(FinalProject.ServiceReference1.city c) {
            return base.Channel.AddcityAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddtypmanuiAsync(FinalProject.ServiceReference1.typ_menuyim_price_ t) {
            return base.Channel.AddtypmanuiAsync(t);
        }
        
        public System.Threading.Tasks.Task<int> AddlessonAsync(FinalProject.ServiceReference1.Chugim c) {
            return base.Channel.AddlessonAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> GetNumLessonfreeAsync(int codeManuy) {
            return base.Channel.GetNumLessonfreeAsync(codeManuy);
        }
        
        public System.Threading.Tasks.Task<int> delateAsync(FinalProject.ServiceReference1.castumeres c) {
            return base.Channel.delateAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> delatguaidAsync(FinalProject.ServiceReference1.gauides g) {
            return base.Channel.delatguaidAsync(g);
        }
        
        public System.Threading.Tasks.Task<int> delatecieyAsync(FinalProject.ServiceReference1.city c) {
            return base.Channel.delatecieyAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> delatetypchugAsync(FinalProject.ServiceReference1.typ_chugim t) {
            return base.Channel.delatetypchugAsync(t);
        }
        
        public System.Threading.Tasks.Task<int> AddlesontomanuiAsync(FinalProject.ServiceReference1.rishum_to_lesson r) {
            return base.Channel.AddlesontomanuiAsync(r);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FinalProject.ServiceReference1.rishum_to_lesson>> GetAlrishumAsync() {
            return base.Channel.GetAlrishumAsync();
        }
        
        public System.Threading.Tasks.Task<int> AddgauidAsync(FinalProject.ServiceReference1.gauides g) {
            return base.Channel.AddgauidAsync(g);
        }
        
        public System.Threading.Tasks.Task<int> GetCodtogauidAsync() {
            return base.Channel.GetCodtogauidAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfService/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
